name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  integration_test_android:
    name: Run Flutter Android Integration Tests
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      matrix:
        version: ["3.x"]
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run flutter android integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          ram-size: 2048M
          heap-size: 4096M
          disk-size: 8192M
          script: |
            flutter doctor -v && cd example && flutter drive --driver=test_driver/integration_test.dart --target=integration_test/http_proxy_override_test.dart

  integration_test_ios:
    name: Run Flutter iOS Integration Tests
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      matrix:
        version: ["3.x"]
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14 Pro Max'
      - run: |
          flutter doctor -v
          cd example
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/http_proxy_override_test.dart